### ISSUE TITLE
可以让ip自动更新不，在goagent里面？

### ISSUE THREAD

**Issue by iMingLei** [out0fmemory/GoAgent-Always-Available#1]
如题。

**Comment by out0fmemory** [comment]
下一步会加入脚本，实现一键替换功能，comming......

**Comment by zouchengjun** [comment]
goagent,贴在hosts之后，没有用啊

回复： 我本地是在3.0.9a试的，放到host可以，你这是那个版本的？

**Comment by out0fmemory** [comment]
我本地是在3.0.9a试的，放到host可以，你这是那个版本的？
