### ISSUE TITLE
版主，能发布一下爱普宽带的高稳定性Ip吗？

### ISSUE THREAD

**Issue by yuan18** [out0fmemory/GoAgent-Always-Available#12]
如题所写

**Comment by out0fmemory** [comment]
我这边么有爱普的网络，所以就没有扫描了，建议你下载工程，使用local\gscan目录下的gscan扫描一下可用ip，cd 到gscan目录后，使用gscan.exe -iprange="./my.conf" 进行扫描，扫描完之后可用ip在google_ip.txt文件中
