### ISSUE TITLE
没有发现gscan在扫描ip表

### ISSUE THREAD

**Issue by yangchangyz** [out0fmemory/GoAgent-Always-Available#14]
没有发现gscan在扫描ip表，只看到显示从服务器下载的ip，不会自己扫，自己扫的ip在哪个文件输出呢？真的不懂，求教·······

**Comment by out0fmemory** [comment]
gscan扫描工具在本项目的local/gscan目录，下载后命令行cd到这个目录，然后运行gscan.exe -iprange="./my.conf"即可，扫描完成后ip文件在google_ip.txt中，把这个替换到GoAgent里的地址列表即可

**Comment by liugang1014** [comment]
5月份又失效了一批

**Comment by out0fmemory** [comment]
哦，那我近期在更新一下ip段文件吧，你暂时先用已经扫出来的地址

**Comment by liugang1014** [comment]
现在没有一个可用的  贴点可以用的吧

**Comment by out0fmemory** [comment]
不会吧，每天更新上传的ip列表文件也不可用？

**Comment by fhzyfjy** [comment]
```
更新googleip地址于160417，增加了不少ip地址，从中应该可以扫出不少ip。是不是该更新一下了，谢谢楼主
```

**Comment by out0fmemory** [comment]
马上会在更新一批,有一台vps在扫描全网的可用谷歌ip,但是需要很久(大半个月.....)
