### ISSUE TITLE
很好，可以用，谢谢

### ISSUE THREAD

**Issue by dlzdwxdt** [out0fmemory/GoAgent-Always-Available#17]
之前我甚至认为goagent都已经不能用了，无意间找到你的这个项目发现里面竟然还有可以用的IP，速度还挺快，很感谢，不过文件夹里的gscan工具貌似扫不出来IP，我将你提供的scan程序创建了一个快捷方式然后在目标最后头加了你提供的参数 -iprange="./my.conf"，并以管理员身份运行，但是一直卡在start scan ning可用IP那一块，卡了很久（卡了一个小时吧，我就给关了），配置文件参数我稍稍改了一下，scanworks改成了30，其余的没有动，请问这是什么情况？能否指点一下我，还有那个googleip.txt文件怎么导入到gogotester内部？能否教一下我

**Comment by liu246542** [comment]
@dlzdwxdt 
我目前是用命令行的方式，在gscsn目录下打开命令行窗口，敲入gscan.exe -iprange="./my.conf"，直接扫描ip，没有用管理员方式运行。
配置文件里，scanwork 大概是线程，一般越高扫描出的越快，对电脑负荷越高，我自己设置的是500，30的偏低了
google_ip.txt的导入，可以直接在goagent的local文件夹下新建一个proxy.user.ini文件，键入以下内容：
 _**[iplist]
google_cn = google_ip.txt中的内容
google_hk = google_ip.txt中的内容**_
没有必要导入到gogotester内部

**Comment by dlzdwxdt** [comment]
@liu246542 
找到原因了，我的防火墙规则没有配置好，把gscan给ban掉了，规则配置好了，现在没问题了。
个人认为配置快捷方式的方法简单一些，直接双击就可以扫描。
线程数我故意调小的，默认的只扫到3个IP就停止，我给改到20个

**Comment by out0fmemory** [comment]
线程数可以根据机器性能调一下,不宜太大(太大失败率增加会导致好ip漏掉),ip数根据自己需求就好啦 .目前我是配置的扫尽量多的ip

**Comment by dlzdwxdt** [comment]
@out0fmemory 
刚刚才发现goagent服务端无法上传了，提示信息为
Error 404: --- begin server output ---
https://developers.google.com/accounts/docs/AuthForInstalledApps
挂了代理也上传不上去，貌似验证机制改了，怎么办呀现在？

**Comment by liu246542** [comment]
@dlzdwxdt github上有一个xx-net项目，里面有新的上传代码，我把它上传到了百度云，
下载地址：
链接: http://pan.baidu.com/s/1pLOtyyB 密码: xps5
