### ISSUE TITLE
隐藏 ip list

### ISSUE THREAD

**Issue by jasonslyvia** [out0fmemory/GoAgent-Always-Available#2]
建议 ip list ignore 掉，再通过其它更稳妥的方式展现出来（丢在服务器上脚本里自动去加载？）

否则这么赤裸裸的暴露出来，被墙的几率又会大很多吧……

**Comment by out0fmemory** [comment]
1、考虑到目前直接下载替换ip的人较多，暂时没做，因为加密什么的需要脚本
2、其实最根本被墙的原因是用这些ip的人变多，而不是是否是明文展示的ip list
