### ISSUE TITLE
一堆中国人搞的垃圾

### ISSUE THREAD

**Issue by au1201** [out0fmemory/GoAgent-Always-Available#21]
最擅长的就是把自己的名字写到文件里面，而事情是做不出来的

**Comment by out0fmemory** [comment]
你又何出此言，有问题说问题，况且开源的项目对你没帮助或者不好你自己搞一个呗

**Comment by 935352** [comment]
最不缺的就这种键盘侠喷子狗

**Comment by blob2015** [comment]
@out0fmemory 
看看 au1201 之流，“斗米恩，担米仇”。老兄是否考虑过滤掉一些只知道衣来伸手、饭来张口的家伙？那种家伙，固然不是都是如此凉薄、无礼、无耻、动物，但是否太过偏多？

**Comment by PvCDp** [comment]
不要理会这种人，我支持博主！

**Comment by Prussia** [comment]
au1201用github写hello world。。这水平呵呵

**Comment by goldenfreemanchina** [comment]
Just fule Prussia~~MieHAHAHA~~~
