### ISSUE TITLE
chrome上https过不去咋办

### ISSUE THREAD

**Issue by Prussia** [out0fmemory/GoAgent-Always-Available#22]
显示不是私密连接

**Comment by liu246542** [comment]
导入local文件夹下的CA证书，导入到受信任的根证书颁发机构即可

**Comment by out0fmemory** [comment]
楼上正解，由于GoAgent使用了自己生成的证书，正常情况下是不被浏览器接受的，需要手动导入一下GoAgent生成的证书（注：如果GoAgent根目录下没有CA.crt文件，先运行一下GoAgent即可生成，然后再导入）
