### ISSUE TITLE
请问电信 铁通 阿里云这些ip文件是什么

### ISSUE THREAD

**Issue by Celthi** [out0fmemory/GoAgent-Always-Available#23]
这些文件是说在电信或者铁通ISP中的google可用IP吗

**Comment by out0fmemory** [comment]
对的，分别用不同线路扫描到的，用对应的可能效果好点~也可以用阿里云的，因为阿里云是多线服务器线路

**Comment by Celthi** [comment]
噢噢，对了，我用了这些IP后，出现![You connection is not private](https://blog.iyin.me/wp-content/uploads/2014/12/Screen-Shot-2014-11-28-at-12.52.17-PM.png)，不能访问，是因为证书的原因吗？Windows平台，使用管理员运行过，但是没有用，是不是需要chrome手动导入证书，还是这些IP有是不太安全的？

**Comment by out0fmemory** [comment]
需要在chrome里边导入证书的，你可以查查教程
