### ISSUE TITLE
ip list    在心版本的放在哪里为好？

### ISSUE THREAD

**Issue by whhxmwhh** [out0fmemory/GoAgent-Always-Available#24]
找不到您介绍的目录

**Comment by out0fmemory** [comment]
goagent目录下有个proxy.ini吧？里边[iplist]下面的google_cn和google_hk后面的地址替换为从这里下载的可用地址就ok

建议你直接用本项目的local文件夹，这个是可以自动拉取可用ip的，开箱即用，enjoys!

**Comment by Jan9th** [comment]
@out0fmemory local目录和 goagent-orignal\local目录下都有这个文件,不知道是哪个

**Comment by out0fmemory** [comment]
是local目录下的，goagent-orignal这个目录是从原始的GoAgent项目拉过来的，用来给大家对比的，表明我是没有恶意修改滴

**Comment by hwbasd** [comment]
支持下。。。。。
