### ISSUE TITLE
请教一个小小的简单的问题哈

### ISSUE THREAD

**Issue by theratlesnake** [out0fmemory/GoAgent-Always-Available#26]
电信的网络，可以使用铁通的ip吗？谢谢

**Comment by out0fmemory** [comment]
可以是可以，但是很容易失效，建议用阿里云那个，这个服务器应该是做过双线优化的，会好些

**Comment by theratlesnake** [comment]
阿里云？？是谷歌公司的，还是阿里公司的哦？

**Comment by out0fmemory** [comment]
阿里云自然是阿里的啦，我是说这些可用ip是用阿里云的服务器扫描出来的，因为服务器是双线接入，所以理论上扫描出来的ip对电信用户和联通用户都是更好一些

**Comment by theratlesnake** [comment]
噢噢，好吧好吧，谢啦
