### ISSUE TITLE
打开的时候提示获取可用ip失败

### ISSUE THREAD

**Issue by tengge1** [out0fmemory/GoAgent-Always-Available#28]
提个bug，上次关闭时未设为禁用代理，下次打开的时候提示获取可用ip失败，然后报错。
下载github上的可用ip
下载yanke.info上的可用ip
下载github上的可用ip
下载yanke.info上的可用ip
下载github上的可用ip
下载yanke.info上的可用ip
获取可用ip失败
INFO - [May 29 21:51:13] get github first setup Ips: None
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "proxy.py", line 1538, in <module>
    common = Common()
  File "proxy.py", line 1369, in __init__
    self.IPLIST_ALIAS = collections.OrderedDict((k, iplist.split('|') if v else []) for k, v in oriIpList)
  File "D:\Program Files (x86)\goagent-forever\local\python27.zip\collections.py", line 52, in __init__
  File "D:\Program Files (x86)\goagent-forever\local\python27.zip\_abcoll.py", line 566, in update
  File "proxy.py", line 1369, in <genexpr>
    self.IPLIST_ALIAS = collections.OrderedDict((k, iplist.split('|') if v else []) for k, v in oriIpList)
AttributeError: 'list' object has no attribute 'split'

**Comment by tengge1** [comment]
使用goagent打开github时有时会报这个错误：

Error: Not Found

The requested URL /_gh/ was not found on this server.

**Comment by tengge1** [comment]
更换新版后第一个问题没有了。

**Comment by out0fmemory** [comment]
第二个问题还有吗？你是用项目里local直接运行的还是自己部署的gae id

**Comment by tengge1** [comment]
我自己的gae id，在公司试了一下没问题，晚上回家我再试试。

**Comment by out0fmemory** [comment]
如果真是这个提示，那原因就是没部署好，或者服务器部署的版本和本地用的版本不一致，使用server目录的工具重新部署一下就好

**Comment by tengge1** [comment]
家里的还是不行。访问 https://www.tensorflow.org/返回了404。明明有39个good ip，连接的时候却几乎全部是bad ip。我重新部署一些服务端试试。

INFO - [Jun 05 22:17:59] extend_iplist start for hosts=[]
INFO - [Jun 05 22:17:59] extend_iplist finished, added 231
INFO - [Jun 05 22:18:15] ssl good_ipaddrs=39, bad_ipaddrs=54, unknown_ipaddrs=0
INFO - [Jun 05 22:18:16] 127.0.0.1:51089 "GAE GET https://www.tensorflow.org/ HT
TP/1.1" 404 281
INFO - [Jun 05 22:18:17] 127.0.0.1:51095 "DIRECT POST https://clients4.google.co
m/chrome-sync/command/?client=Google+Chrome&client_id=51VOFTPTVptRCSl55aCZAQ%3D%
3D HTTP/1.1" 200 -
INFO - [Jun 05 22:18:17] ssl good_ipaddrs=41, bad_ipaddrs=54, unknown_ipaddrs=0
INFO - [Jun 05 22:18:18] 127.0.0.1:51095 "DIRECT POST https://clients4.google.co
m/chrome-sync/command/?client=Google+Chrome&client_id=51VOFTPTVptRCSl55aCZAQ%3D%
3D HTTP/1.1" 200 -
WARNING - [Jun 05 22:18:21] bad IP: ('202.160.9.176', 443) (timeout('timed out',
))
WARNING - [Jun 05 22:18:21] bad IP: ('181.30.242.237', 443) (timeout('timed out'
,))

**Comment by caofengzi** [comment]
有時候的確有這個問題，但是俺多更新幾次就可以了，不知道你那裡是否可以？
