### ISSUE TITLE
linux中如何显示通知图标？

### ISSUE THREAD

**Issue by ghost** [out0fmemory/GoAgent-Always-Available#34]
用的manjaro，只有在终端中运行才能方便的看状态，一不小心就容易关错了。。。
是linux中压根就是不显示通知栏图标的，还是我的打开方式不对？？？

**Comment by out0fmemory** [comment]
试试goagent-gtk.py，应该有些依赖项，解决下就好

**Comment by ghost** [comment]
确实可以！Thanks！
python2 ./local/goagent-gtk.py
会提示需要安装python-vte，实际上需要装的是vte，运行后就有通知栏图标了！
当然，没有装python2-pyopenssl的还是要装的。
再次感谢！

**Comment by pengweipro** [comment]
@out0fmemory 求问有什么方法让vte透明么？
我在goagent-gtk.py中286行后面插了一句：
terminal.set_backgroud_transparent(gtk.TRUE)
可也只能让vte透明出桌面壁纸来，而非xfce4-terminal一样的透明可见后面的窗口。
或者，可以调用xfce4-terminal也好（我就一小白，不会写代码啊）

**Comment by pengweipro** [comment]
增补：（适用于vte版本0.28）
goagent-gtk.py，286行后插入：
    terminal.set_opacity(透明度)
    colormap = window.get_screen().get_rgba_colormap()
    if colormap == None:
    	colormap = window.get_screen().get_rgb_colormap()
    gtk.widget_set_default_colormap(colormap)
可以让vte的窗口透明，透明度范围0-65535，0为全透明。

**Comment by ghost** [comment]
不好意思，我又有问题了。。。
事情是这样的，前一段时间，发现goagent-gtk.py首次运行的时候没有任务栏图标出现，以为没有运行起来，就又点了一次（我建了个快捷方式）。任务栏图标是出现了，可是点开窗口发现多了一行：
「socket.error: [Errno 98] Address already in use」
还有，只要不重启，退出后再运行就可以一次出现任务栏图标，但这个错误提示还是会出现！！！
我退出后还特意看过进程管理器里，确实是没了goagent-gtk.py这个进程的。
每次都要点击两次才出现任务栏图标，我以为是时间长了系统出了问题，就没当回事。
可是这两天重做了系统，同样的环境，还是需要两次才出现任务栏图标！
是更新了什么导致的么，还是我装的什么软件跟它冲突？
##########################################################################
补充：在bash终端下运行goagent-gtk.py，倒是没有错误了，但不在本终端窗口中提示状态了，还不能关，关了就退了，郁闷了。
##########################################################################
sorry，找到原因了：
要加上python2.7就没错误提示了-_-|||
没加的时候能运行，就忘了这回事。。。
##########################################################################
更新，问题再次出现，这次可能的原因是，「装了switchyomega插件的vivaldi浏览器处于打开状态」，
但尝试复现失败！
可以确认的是，之前认为的「缺少python2.7」只是诱因，不是真正的罪魁祸首。
