### ISSUE TITLE
goagent-gtk是否与steam有某些方面冲突？

### ISSUE THREAD

**Issue by ghost** [out0fmemory/GoAgent-Always-Available#47]
OS: Manjaro 17.0.2
Kernel: x86_64 Linux 4.9.39-1-MANJARO
DE: Xfce4
CPU: Intel Core i5-4200U @ 4x 2.6GHz
GPU: GeForce GT 730M
（截取自screenfetch）

之前曾经发生过几次这样的事：
刚刚登入桌面，使用过「goagent-gtk.py」之后（已经退出），steam便无法打开了，只有重启才行。
当时就怀疑是steam跟goagnet-gtk有冲突，因为仅有几次非重启不可的情况，便不敢确定。

而就刚刚，steam怎么都无法登入服务器（多次杀死进程后重试，依旧无法登入），
后来想起goagent-gtk开着呢，于是退了goagent-gtk，再试，可以登入steam了。

这么说来，几乎可以肯定goagent-gtk与steam有某种冲突了，至少在linux上如此。
具体是怎么回事呢？
有没有方法解决呢？

**Comment by out0fmemory** [comment]
这样的话建议你直接运行python proxy.py就可以了，在cmd命令行local文件夹目录运行

**Comment by ghost** [comment]
也不行，刚退出steam，开了proxy.py，就登不上去了，关了terminal之后，就能登了。
看steam的说明，就那么几个端口，按理说应该没有什么冲突才对。
难道是ssl？（我不懂，猜的）

**Comment by ghost** [comment]
呃。。。
这个，必须得补充一下了：
steam更新了一下，变成英文了，然后，我突发奇想地试了一下，goagent-gtk运行的时候也能登入了！！！

又试了一下，改成中文后，就没法在goagent-gtk开着的时候登入，
再改回英文，就可以在goagent-gtk运行状态下登入！！！

再次，steam无法登入，从任务管理中提示的进程信息来看，语言是en-US没错。
接下来准备多次尝试。

汗。。。
玩了一会儿之后，又改回中文，goagent-gtk未退出的情况下，成功登入了。。。
难道这是电信的锅？？？

**Comment by pengweipro** [comment]
又试了一下，改成中文后，就没法在goagent-gtk开着的时候登入，
再改回英文，就可以在goagent-gtk运行状态下登入！！！

**Comment by ghost** [comment]
算了，反正我想登的时候总有办法能登成，就这么着吧。。。
