### ISSUE TITLE
有问题的字段反馈

### ISSUE THREAD

**Issue by fredericky123** [out0fmemory/GoAgent-Always-Available#52]
![1](https://user-images.githubusercontent.com/13982749/29397294-c7d0a4f2-834f-11e7-8f97-1ea408d47138.PNG)
如图，google ip字段这里有错误的地方，大大可以删去这段哎

**Comment by caofengzi** [comment]
也許是暫時ping不通了，以後可能還能用。

**Comment by fredericky123** [comment]
不是的 截图里显示的出现了一堆文字乱码 不是ip段 应当删除这几行吧

**Comment by out0fmemory** [comment]
今天晚上修复下

**Comment by out0fmemory** [comment]
多谢提醒，fixed
