### ISSUE TITLE
新bug

### ISSUE THREAD

**Issue by caofengzi** [out0fmemory/GoAgent-Always-Available#55]
使用最新分支版鏈接提示502錯誤。

Message From LocalProxy
Local URLFetch 'https://botanwang.com/' failed

need more than 2 values to unpack
need more than 2 values to unpack
![2017-08-19_155522](https://user-images.githubusercontent.com/13650252/29484721-19290206-84f7-11e7-8b29-3df24b155b0c.png)

**Comment by out0fmemory** [comment]
是不是客户端和服务器不对应？
我这里是正常的

**Comment by caofengzi** [comment]
好了，應該是proxy.ini哪裡配置錯誤引起的,或者是舊版proxy.ini與新版版匹配。
