### ISSUE TITLE
goproxy版自动搜谷歌IP的么？

### ISSUE THREAD

**Issue by mymatrix2002** [out0fmemory/GoAgent-Always-Available#56]
找了很久现在找到能自动搜谷歌IP的都是以goagent为基础的，现在goagent的作者都开始开发goproxy了，希望社长能出一个goproxy版自动搜谷歌IP的版本。

**Comment by out0fmemory** [comment]
有这个考虑，不过也.要.看.历.史.的.进.程.呀，比如goproxy就自己搞了扫描什么的。。。

**Comment by name2008less** [comment]
社长说过了  短期内不会考虑自动扫描功能  这个短期 基本就是没有希望了  因为他每次都说抽空完善autorange 然后现在都已经一年多了吧。。。。。 依然没有动静


我想社长主要是想抑制goproxy的传播范围才不做的吧 如果像xxnet一样这么简单易用  用户量会瞬间激增
喝茶什么的可能就要找上来了。。。。   所以才会故意提高使用门槛   看看xxnet的issues数量和goproxy的就知道了。  前一阵子社长还故意关了项目以避风头呢。       不过也要理解人家 毕竟无偿做这个的  还要承担请去喝茶的风险   所以能用就用吧

**Comment by name2008less** [comment]
当然我也是希望有一个集成自动扫描功能的版本  确实方便啊

**Comment by phuslu** [comment]
额，在 goproxy 上我觉得我不欠所有人的，所以才会显得有点任性。

至于喝茶，在做 GoAgent 的时候我已经被被喝过了。。。

**Comment by name2008less** [comment]
你这很是任性啊，被警告过了又另立山头😄
