### ISSUE TITLE
使用说明中提到替换IP在proxy.ini文件中[hosts]一节，应该是[iplist]小节吧？

### ISSUE THREAD

**Issue by andnot** [out0fmemory/GoAgent-Always-Available#7]
不知是否是版本问题，我使用的Goagent的proxy.ini文件中，更换IP地址都是在[iplist]小结。

**Comment by out0fmemory** [comment]
应该是由于goagent版本更新导致的，是一样的含义

**Comment by yisuoyanyu111** [comment]
能用就行，Goagent版本太多了！

**Comment by out0fmemory** [comment]
对的，goagent版本太多了，后面我准备在这个项目集成一个自动化的可用的版本供大家使用

**Comment by andnot** [comment]
哦，那太好了！
多亏了你提供的IP地址，我的goagent现在又可以用了~
非常感谢！
