### ISSUE TITLE
为什么没有联通的稳定高速的ＩＰ呢？

### ISSUE THREAD

**Issue by carolusliu** [out0fmemory/GoAgent-Always-Available#8]
为什么没有联通的稳定高速的ＩＰ呢？楼主只更新电信和铁通的。怎么没有联通的ＩＰ呢

**Comment by out0fmemory** [comment]
因为我没有联通的线路>_<,，欢迎随时post，后面准备搞个大家分享ip的机制

**Comment by out0fmemory** [comment]
现在已经上传了扫描工具以及配置文件，可以自己扫咯。后续此项目将支持自动扫
