### ISSUE TITLE
您好，您的IP很好用，非常感谢，不过自从昨天 早上提示“您的链接不是私密链接”我换了IP后，却再也传不了视频到youtube或则谷歌Drive了，您知道这是怎么回事吗？该怎么解决呢？

### ISSUE THREAD

**Issue by hwp994108018** [out0fmemory/GoAgent-Always-Available#9]
您好，您的IP很好用，非常感谢，不过自从昨天 早上提示“您的链接不是私密链接”我换了IP后，却再也传不了视频到youtube或则谷歌Drive了，您知道这是怎么回事吗？该怎么解决呢？

**Comment by out0fmemory** [comment]
根据我的了解，这应该是使用了类似chrome的浏览器，由于浏览器没有导入goagent的证书，浏览器认为goagent是不安全的，你可以参考https://github.com/XX-net/XX-Net/wiki/GoAgent-Import-CA 里的说明导入goagent 的证书，记得导入完成后重启浏览器生效
